name: CD Pipeline Prod

on:
  push:
    branches:
      - prod  # Déclenchement sur la branche prod

env:
  IMAGE_NAME: intranet-newdeal
  DOCKER_REGISTRY: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  # ==========================================
  # JOB 1 - SCAN : Sécurité avant déploiement
  # ==========================================
  security_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Scan Image for Vulnerabilities (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest'
          exit-code: '1' # Bloque si vulnérabilité CRITICAL
          severity: 'CRITICAL'

  # ==========================================
  # JOB 2 - DEPLOY : Déploiement sur runner Windows
  # ==========================================
  deploy:
    needs: security_scan
    runs-on: self-hosted
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull and Run on Port 80
        run: |
          # Téléchargement de l'image
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
          
          # Nettoyage de l'ancien conteneur (Syntaxe compatible PowerShell/Windows)
          $container = docker ps -a -q --filter "name=intranet-prod"
          if ($container) {
              docker stop intranet-prod
              docker rm intranet-prod
          }
          
          # Lancement sur le port 80 (Demande Etape 4)
          docker run -d --name intranet-prod -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest

  # ==========================================
  # JOB 3 - NOTIFY : Notification Email (Etape 5)
  # ==========================================
  notify:
    needs: deploy
    runs-on: ubuntu-latest
    if: always() # S'exécute même si le déploiement échoue
    steps:
      - name: Send Deployment Status Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USER }}
          password: ${{ secrets.MAIL_PASS }}
          subject: "Rapport Déploiement Intranet : ${{ job.status }}"
          body: "Le déploiement de l'Intranet New Deal est terminé avec le statut : ${{ job.status }}."
          to: moussawade@groupeisi.com
          from: "GitHub Actions - Ministère Communication"
